#CREATE DATABASE Country_test;
#DROP DATABASE Country_test;
USE Country_test;
CREATE TABLE Currencies(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CurrancyName NVARCHAR(30) NOT NULL,
    Symbol NVARCHAR(5) NOT NULL
)ENGINE=INNODB;
CREATE TABLE Languages(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LanguageName NVARCHAR(30) NOT NULL
)ENGINE=INNODB;
CREATE TABLE Countries(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CountryName NVARCHAR(20) NOT NULL,
    Alpha2Code NVARCHAR(2) NOT NULL,
    CallingCode NVARCHAR(4) NOT NULL,
    Capital NVARCHAR(20) NOT NULL,
    Region NVARCHAR(10) NOT NULL,
    SubRegion NVARCHAR(30) NOT NULL,
    CountryPopulation INT UNSIGNED NOT NULL,
    Lat DECIMAL(18,0) NOT NULL,
    Lng DECIMAL(18,0) NOT NULL,
    Area DECIMAL(18,0) NOT NULL,
    Flag NVARCHAR(150) NOT NULL
)ENGINE=INNODB;
CREATE TABLE Boarder(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Countryid INT NOT NULL,
    FOREIGN KEY (Countryid) 
		REFERENCES Countries(id),
    BoarderCount INT NOT NULL
)ENGINE=INNODB;
CREATE TABLE CurrencyPerCountry(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FOREIGN KEY (Countryid) REFERENCES Countries(id),
    FOREIGN KEY (Currencyid) REFERENCES Currencies(id)
)ENGINE=INNODB;
CREATE TABLE LanguagePrCountry(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FOREIGN KEY (Languageid) REFERENCES Languages(id),
    FOREIGN KEY (Countryid) REFERENCES Countries(id)
)ENGINE=INNODB;